import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'
import { Navigation } from '@/components/Navigation/Navigation';

const inter = Inter({ weight: ["500", "600"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="barContainer">
          <div className="wrapper">
            <Navigation />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
